# Generated by Django 4.2 on 2025-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="pre_requisite",
            field=models.ManyToManyField(
                blank=True, related_name="successor_courses", to="main.course"
            ),
        ),
    ]
